name: Deploy Flask App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip the application files
        run: zip -r flask_app.zip . -x "*.git*"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "marks-predict"
          slot-name: "production"
          package: "./flask_app.zip"
